name: .NET build & release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build self-contained osx-arm64
      run: dotnet publish --self-contained true -r osx-arm64 -c Release -o out
    - name: Build self-contained win-x64
      run: dotnet publish --self-contained true -r win-x64 -c Release -o out
    - name: Build self-contained linux-x64
      run: dotnet publish --self-contained true -r linux-x64 -c Release -o out
    - name: GitHub Releases
      uses: fnkr/github-action-ghr@v1.3
      env:
        GHR_COMPRESS: xz
        GHR_PATH: out/
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
